[versions]
android-gradle-plugin = "8.2.2"
hilt-android = "2.51"
kotlin-android = "1.9.22"
lifecycle = "2.7.0"
navigation = "2.7.7"
org-jetbrains-kotlin-jvm = "1.9.22"
kotlin-corountines = "1.8.0"
retrofit = "2.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
junit-junit = "4.13.2"
androidx-test-ext-junit115 = "1.1.5"
androidx-test-espresso-espresso-core = "3.5.1"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.require = "1.12.0" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.require = "1.8.2" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.require = "1.6.2" }

#Lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

#XML
appcompat = { group = "androidx.appcompat", name = "appcompat", version.require = "1.6.1" }
material = { group = "com.google.android.material", name = "material", version.require = "1.11.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.require = "2.1.4" }

#Inject
javax-inject = { module = "javax.inject:javax.inject", version.require = "1" }

#Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }

#Coroutines
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-corountines" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-corountines" }

#Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

#ViewBindingPropertyDelegate
view-binding-property-delegate-noreflection = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.require = "1.5.9" }

#Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-convertor-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

#OkHttp
okhttp3-bom = {group = "com.squareup.okhttp3", name = "okhttp-bom", version.require = "4.12.0"}
okhttp3 = {group = "com.squareup.okhttp3", name = "okhttp" }
okhttp3-logging-interceptor = {group = "com.squareup.okhttp3", name = "logging-interceptor" }

junit = { group = "junit", name = "junit", version.ref = "junit-junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit115" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-espresso-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-android" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }

[bundles]
lifecycle = ["lifecycle-runtime-ktx", "lifecycle-livedata-ktx", "lifecycle-viewmodel-ktx", "lifecycle-viewmodel-savedstate"]
navigation = ["navigation-fragment-ktx", "navigation-ui-ktx"]
okhttp3 = ["okhttp3", "okhttp3-logging-interceptor"]